[package]
name = "sdkwork-agents-gateway-assembly"
edition.workspace = true
license.workspace = true
version.workspace = true
description = "Generated gateway assembly for sdkwork-agents application HTTP plane."

[lib]
name = "sdkwork_agents_gateway_assembly"
path = "src/lib.rs"

[dependencies]
axum.workspace = true
tokio.workspace = true
anyhow.workspace = true
sdkwork-agent-server.workspace = true
sdkwork-agents-kernel-bridge.workspace = true
sdkwork-routes-agents-app-api.workspace = true
sdkwork-routes-agents-backend-api.workspace = true
sdkwork-routes-agents-http-shared.workspace = true
sdkwork-routes-agents-open-api.workspace = true
