apiVersion: v1
kind: Service
metadata:
  name: sdkwork-intelligence-agents-worker
  labels:
    app.kubernetes.io/name: sdkwork-agents
    app.kubernetes.io/component: task-worker
spec:
  selector:
    app.kubernetes.io/name: sdkwork-agents
    app.kubernetes.io/component: task-worker
  ports:
    - name: operations
      port: 8096
      targetPort: operations
  type: ClusterIP
