//! Generated API assembly bootstrap for sdkwork-agents.
//! Regenerated by pnpm api:assembly:materialize.
//!
//! Multi-surface merges mount shared infrastructure routes once at the assembly layer
//! so `/healthz`, `/livez`, `/readyz`, and `/metrics` are not duplicated per surface.

use axum::Router;

pub struct ApiAssembly {
    pub router: Router,
}

pub async fn assemble_api_router(state: AgentHttpState) -> ApiAssembly {
    let mut router = Router::new();
    router = router.merge(sdkwork_routes_agents_app_api::gateway_mount(state.clone()).await);
    router = router.merge(sdkwork_routes_agents_backend_api::gateway_mount(state.clone()).await);
    router = router.merge(sdkwork_routes_agents_open_api::gateway_mount(state.clone()).await);
    ApiAssembly { router }
}
