use sdkwork_intelligence_agents_service::{
    AgentBusinessIdGenerator, AgentIdGenerator, SQL_INSERT_AGENT,
    SQL_INSERT_AGENT_COMPOSITION_SLOT, SQL_INSERT_AGENT_PROVIDER_BINDING, SQL_INSERT_AUDIT_EVENT,
};

#[test]
fn agent_business_id_generator_uses_signed_safe_snowflake_ids() {
    let generator = AgentBusinessIdGenerator::with_node_id(42)
        .expect("valid snowflake node id should initialize");

    let first = generator
        .next_id()
        .expect("first snowflake id should generate");
    let second = generator
        .next_id()
        .expect("second snowflake id should generate");

    assert!(first > 0);
    assert!(second > first);
    assert!(first <= i64::MAX as u64);
    assert_eq!(42, AgentBusinessIdGenerator::decode_node_id(first));
    assert!(AgentBusinessIdGenerator::decode_timestamp_delta_millis(first) > 0);
}

#[test]
fn postgres_runtime_insert_sql_binds_ids_explicitly_for_all_business_tables() {
    for (name, sql) in [
        ("ai_agent", SQL_INSERT_AGENT),
        (
            "ai_agent_runtime_binding",
            SQL_INSERT_AGENT_PROVIDER_BINDING,
        ),
        ("ai_agent_audit_event", SQL_INSERT_AUDIT_EVENT),
        (
            "ai_agent_composition_slot",
            SQL_INSERT_AGENT_COMPOSITION_SLOT,
        ),
    ] {
        let prefix = format!("INSERT INTO {name} (id, ");
        assert!(
            sql.starts_with(&prefix),
            "{name} insert must bind snowflake id explicitly: {sql}"
        );
        assert!(
            !sql.contains("nextval") && !sql.contains("RETURNING id"),
            "{name} insert must not allocate ids through database side effects"
        );
    }
}

#[test]
fn postgres_agent_business_schema_does_not_define_database_generated_ids() {
    let ddl = include_str!("../../../database/ddl/baseline/postgres/0001_agents_baseline.sql");

    assert!(!ddl.contains("GENERATED BY DEFAULT AS IDENTITY"));
    assert!(!ddl.contains("BIGSERIAL"));
    assert!(!ddl.contains("SERIAL PRIMARY KEY"));
    assert!(!ddl.contains("nextval("));

    for table in [
        "ai_agent",
        "ai_agent_runtime_binding",
        "ai_agent_composition_slot",
        "ai_agent_audit_event",
    ] {
        let create_table = format!("CREATE TABLE IF NOT EXISTS {table} (");
        assert!(ddl.contains(&create_table), "missing table DDL for {table}");
    }
}
