-- SDKWork agents consolidated initialization baseline (postgres)
-- Generated by reset-database-initialization-state.mjs
-- Application is in initialization state: full DDL lives here; migrations/ is reserved for post-GA changes.

-- baseline source: ddl/baseline/postgres/0001_ai_agent_baseline.sql
-- SDKWork Agents — composition-plane PostgreSQL baseline (v3)
-- Domain: intelligence / agents-platform
-- Contract: database/contract/schema.yaml
-- All tables use the ai_ prefix per DATABASE_SPEC.md.
-- MCP, knowledge, memory, skills, prompts, and drive content are owned by
-- sibling modules. Agents reference them exclusively through
-- ai_agent_composition_slot.
-- 4 core tables: ai_agent, ai_agent_runtime_binding,
-- ai_agent_composition_slot, ai_agent_audit_event.

-- ─────────────────────────────────────────────────────────
-- Helper: validate capabilities JSON is a standard array
-- ─────────────────────────────────────────────────────────
CREATE OR REPLACE FUNCTION sdkwork_intelligence_agents_service_capabilities_json_is_standard(input TEXT)
RETURNS BOOLEAN
LANGUAGE plpgsql
IMMUTABLE
AS $$
DECLARE
    payload JSONB;
BEGIN
    payload := input::jsonb;
    IF jsonb_typeof(payload) <> 'array' THEN
        RETURN FALSE;
    END IF;

    RETURN NOT EXISTS (
        SELECT 1
        FROM jsonb_array_elements(payload) AS capability_values(value)
        WHERE NOT (
            jsonb_typeof(capability_values.value) = 'string'
            AND char_length(capability_values.value #>> '{}') <= 128
            AND (capability_values.value #>> '{}') ~ '^[a-z0-9_-]+(\.[a-z0-9_-]+)+$'
        )
    )
    AND (
        SELECT COUNT(*)
        FROM jsonb_array_elements(payload) AS capability_values(value)
    ) = (
        SELECT COUNT(DISTINCT capability_values.value #>> '{}')
        FROM jsonb_array_elements(payload) AS capability_values(value)
    );
EXCEPTION WHEN others THEN
    RETURN FALSE;
END;
$$;

-- ─────────────────────────────────────────────────────────
-- ai_agent — agent identity, manifest snapshot, lifecycle
-- ─────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS ai_agent (
    id BIGINT NOT NULL PRIMARY KEY,
    uuid VARCHAR(64) NOT NULL,
    tenant_id BIGINT NOT NULL,
    organization_id BIGINT NOT NULL DEFAULT 0,
    owner_user_id BIGINT NOT NULL,
    agent_id VARCHAR(128) NOT NULL,
    code VARCHAR(128) NOT NULL,
    display_name VARCHAR(255) NOT NULL,
    description TEXT,
    manifest_json TEXT NOT NULL,
    manifest_schema_version VARCHAR(32),
    default_code_task_intent_json TEXT,
    implementation_provider_id VARCHAR(128),
    implementation_kind VARCHAR(64),
    implementation_type VARCHAR(64) NOT NULL DEFAULT 'sdkwork-native',
    status SMALLINT NOT NULL,
    visibility SMALLINT NOT NULL,
    tags_json TEXT NOT NULL DEFAULT '[]',
    created_at TIMESTAMPTZ NOT NULL,
    updated_at TIMESTAMPTZ NOT NULL,
    deleted_at TIMESTAMPTZ,
    version BIGINT NOT NULL DEFAULT 0,
    CONSTRAINT uk_ai_agent_uuid UNIQUE (uuid),
    CONSTRAINT uk_ai_agent_tenant_agent_id UNIQUE (tenant_id, agent_id),
    CONSTRAINT uk_ai_agent_tenant_code UNIQUE (tenant_id, code),
    CONSTRAINT ck_ai_agent_implementation_kind CHECK (
        implementation_kind IS NULL OR implementation_kind IN (
            'manifest-only',
            'typed-local-provider',
            'process-adapter',
            'protocol-adapter'
        )
    ),
    CONSTRAINT ck_ai_agent_implementation_type CHECK (
        implementation_type IN (
            'sdkwork-native',
            'rig-rust',
            'openai-agents',
            'langchain',
            'langgraph',
            'crewai',
            'autogen',
            'semantic-kernel',
            'custom'
        )
    ),
    CONSTRAINT ck_ai_agent_implementation_provider_id_standard CHECK (
        implementation_provider_id IS NULL
        OR implementation_provider_id ~ '^provider\.[a-z0-9_-]+(\.[a-z0-9_-]+)*$'
    ),
    CONSTRAINT ck_ai_agent_status CHECK (status IN (0, 1, 2, 3, 4)),
    CONSTRAINT ck_ai_agent_visibility CHECK (visibility IN (0, 1, 2, 3))
);

CREATE INDEX IF NOT EXISTS idx_ai_agent_tenant_org_status_updated
    ON ai_agent (tenant_id, organization_id, status, updated_at DESC);

CREATE INDEX IF NOT EXISTS idx_ai_agent_tenant_owner_status
    ON ai_agent (tenant_id, owner_user_id, status);

-- ─────────────────────────────────────────────────────────
-- ai_agent_runtime_binding — provider / runtime binding
-- ─────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS ai_agent_runtime_binding (
    id BIGINT NOT NULL PRIMARY KEY,
    uuid VARCHAR(96) NOT NULL,
    tenant_id BIGINT NOT NULL,
    organization_id BIGINT NOT NULL DEFAULT 0,
    agent_id VARCHAR(128) NOT NULL,
    binding_id VARCHAR(128) NOT NULL,
    provider_id VARCHAR(128) NOT NULL,
    implementation_kind VARCHAR(64) NOT NULL,
    configuration_profile_id VARCHAR(128) NOT NULL,
    capabilities_json TEXT NOT NULL DEFAULT '[]',
    active BOOLEAN NOT NULL DEFAULT FALSE,
    version BIGINT NOT NULL DEFAULT 1,
    created_at TIMESTAMPTZ NOT NULL,
    updated_at TIMESTAMPTZ NOT NULL,
    CONSTRAINT uk_ai_agent_runtime_binding_uuid UNIQUE (uuid),
    CONSTRAINT uk_ai_agent_runtime_binding_tenant_agent_binding UNIQUE (
        tenant_id,
        agent_id,
        binding_id
    ),
    CONSTRAINT ck_ai_agent_runtime_binding_implementation_kind CHECK (
        implementation_kind IN (
            'manifest-only',
            'typed-local-provider',
            'process-adapter',
            'protocol-adapter'
        )
    ),
    CONSTRAINT ck_ai_agent_runtime_binding_binding_id_standard CHECK (
        binding_id ~ '^binding\.[a-z0-9_-]+(\.[a-z0-9_-]+)*$'
    ),
    CONSTRAINT ck_ai_agent_runtime_binding_provider_id_standard CHECK (
        provider_id ~ '^provider\.[a-z0-9_-]+(\.[a-z0-9_-]+)*$'
    ),
    CONSTRAINT ck_ai_agent_runtime_binding_configuration_profile_id_standard CHECK (
        configuration_profile_id ~ '^profile\.[a-z0-9_-]+(\.[a-z0-9_-]+)*$'
    ),
    CONSTRAINT ck_ai_agent_runtime_binding_capabilities_standard CHECK (
        sdkwork_intelligence_agents_service_capabilities_json_is_standard(capabilities_json)
    )
);

CREATE UNIQUE INDEX IF NOT EXISTS uk_ai_agent_runtime_binding_active_default
    ON ai_agent_runtime_binding (tenant_id, agent_id)
    WHERE active = TRUE;

CREATE INDEX IF NOT EXISTS idx_ai_agent_runtime_binding_tenant_agent_updated
    ON ai_agent_runtime_binding (tenant_id, agent_id, active DESC, updated_at DESC, binding_id ASC);

CREATE INDEX IF NOT EXISTS idx_ai_agent_runtime_binding_tenant_provider
    ON ai_agent_runtime_binding (tenant_id, provider_id);

-- ─────────────────────────────────────────────────────────
-- ai_agent_composition_slot — agent → sibling-module resource references
-- slot_kind / target_module include 'mcp' so agents can bind
-- MCP servers owned by sdkwork-mcp without owning MCP tables.
-- ─────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS ai_agent_composition_slot (
    id BIGINT NOT NULL PRIMARY KEY,
    uuid VARCHAR(96) NOT NULL,
    tenant_id BIGINT NOT NULL,
    organization_id BIGINT NOT NULL DEFAULT 0,
    agent_id VARCHAR(128) NOT NULL,
    slot_id VARCHAR(128) NOT NULL,
    slot_kind VARCHAR(64) NOT NULL,
    target_module VARCHAR(64) NOT NULL,
    target_ref VARCHAR(256) NOT NULL,
    target_version_ref VARCHAR(128),
    priority INTEGER NOT NULL DEFAULT 0,
    enabled BOOLEAN NOT NULL DEFAULT TRUE,
    policy_json JSONB NOT NULL DEFAULT '{}'::jsonb,
    status SMALLINT NOT NULL DEFAULT 1,
    version BIGINT NOT NULL DEFAULT 0,
    created_at TIMESTAMPTZ NOT NULL,
    updated_at TIMESTAMPTZ NOT NULL,
    deleted_at TIMESTAMPTZ,
    CONSTRAINT uk_ai_agent_composition_slot_uuid UNIQUE (uuid),
    CONSTRAINT uk_ai_agent_composition_slot_tenant_agent_slot UNIQUE (tenant_id, agent_id, slot_id),
    CONSTRAINT ck_ai_agent_composition_slot_kind CHECK (
        slot_kind IN ('memory', 'knowledge', 'skill', 'prompt', 'drive', 'tool', 'mcp')
    ),
    CONSTRAINT ck_ai_agent_composition_slot_module CHECK (
        target_module IN ('memory', 'knowledgebase', 'skills', 'prompts', 'drive', 'mcp')
    ),
    CONSTRAINT ck_ai_agent_composition_slot_id_standard CHECK (
        slot_id ~ '^slot\.[a-z0-9_-]+(\.[a-z0-9_-]+)*$'
    ),
    CONSTRAINT ck_ai_agent_composition_slot_status CHECK (status IN (0, 1, 2, 3, 4))
);

CREATE INDEX IF NOT EXISTS idx_ai_agent_composition_slot_lookup
    ON ai_agent_composition_slot (tenant_id, agent_id, slot_kind, enabled, priority, slot_id);

-- ─────────────────────────────────────────────────────────
-- ai_agent_audit_event — immutable management audit log
-- ─────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS ai_agent_audit_event (
    id BIGINT NOT NULL PRIMARY KEY,
    uuid VARCHAR(64) NOT NULL,
    tenant_id BIGINT NOT NULL,
    organization_id BIGINT NOT NULL DEFAULT 0,
    agent_internal_id BIGINT NOT NULL,
    agent_id VARCHAR(128) NOT NULL,
    action VARCHAR(64) NOT NULL,
    subject_id VARCHAR(128) NOT NULL,
    subject_tenant_id VARCHAR(128) NOT NULL,
    request_id VARCHAR(128),
    trace_id VARCHAR(128),
    payload_json TEXT NOT NULL,
    created_at TIMESTAMPTZ NOT NULL,
    CONSTRAINT uk_ai_agent_audit_event_uuid UNIQUE (uuid),
    CONSTRAINT ck_ai_agent_audit_action CHECK (
        action IN (
            'created',
            'updated',
            'deleted',
            'restored',
            'status_changed',
            'started',
            'completed',
            'failed',
            'cancelled',
            'provider_binding_changed',
            'composition_slot_created',
            'composition_slot_updated',
            'composition_slot_deleted'
        )
    )
);

CREATE INDEX IF NOT EXISTS idx_ai_agent_audit_tenant_agent_created
    ON ai_agent_audit_event (tenant_id, agent_id, created_at DESC);

CREATE INDEX IF NOT EXISTS idx_ai_agent_audit_tenant_action_created
    ON ai_agent_audit_event (tenant_id, action, created_at DESC);

-- folded migration: migrations/postgres/0001_ai_agent_core.up.sql
-- Upgrade legacy agents managed-store tables to ai_* composition plane.
-- MCP, knowledge, and memory tables are dropped; their domains are owned by
-- sibling modules (sdkwork-mcp, sdkwork-knowledgebase, sdkwork-memory) and
-- referenced through ai_agent_composition_slot.

-- Rename legacy core tables to ai_* names only if the old table exists
-- and the new table does not (handles databases created before the ai_* baseline).
DO $$
BEGIN
    IF EXISTS (SELECT 1 FROM information_schema.tables WHERE table_name = 'a_agent_business')
       AND NOT EXISTS (SELECT 1 FROM information_schema.tables WHERE table_name = 'ai_agent') THEN
        ALTER TABLE a_agent_business RENAME TO ai_agent;
    END IF;

    IF EXISTS (SELECT 1 FROM information_schema.tables WHERE table_name = 'a_agent_provider_binding')
       AND NOT EXISTS (SELECT 1 FROM information_schema.tables WHERE table_name = 'ai_agent_runtime_binding') THEN
        ALTER TABLE a_agent_provider_binding RENAME TO ai_agent_runtime_binding;
    END IF;

    IF EXISTS (SELECT 1 FROM information_schema.tables WHERE table_name = 'a_agent_deployment')
       AND NOT EXISTS (SELECT 1 FROM information_schema.tables WHERE table_name = 'ai_agent_deployment') THEN
        ALTER TABLE a_agent_deployment RENAME TO ai_agent_deployment;
    END IF;

    IF EXISTS (SELECT 1 FROM information_schema.tables WHERE table_name = 'a_agent_business_audit_event')
       AND NOT EXISTS (SELECT 1 FROM information_schema.tables WHERE table_name = 'ai_agent_audit_event') THEN
        ALTER TABLE a_agent_business_audit_event RENAME TO ai_agent_audit_event;
        ALTER TABLE ai_agent_audit_event RENAME COLUMN agent_business_id TO agent_internal_id;
    END IF;

    IF EXISTS (SELECT 1 FROM information_schema.tables WHERE table_name = 'agents_app_registry')
       AND NOT EXISTS (SELECT 1 FROM information_schema.tables WHERE table_name = 'ai_app_registry') THEN
        ALTER TABLE agents_app_registry RENAME TO ai_app_registry;
    END IF;
END $$;

-- Add columns introduced in the composition plane (idempotent).
ALTER TABLE IF EXISTS ai_agent
    ADD COLUMN IF NOT EXISTS manifest_schema_version VARCHAR(32);

ALTER TABLE IF EXISTS ai_app_registry
    ADD COLUMN IF NOT EXISTS default_agent_id VARCHAR(128);

-- Rename audit column if not already renamed (idempotent).
DO $$
BEGIN
    IF EXISTS (
        SELECT 1 FROM information_schema.columns
        WHERE table_name = 'ai_agent_audit_event' AND column_name = 'agent_business_id'
    ) THEN
        ALTER TABLE ai_agent_audit_event RENAME COLUMN agent_business_id TO agent_internal_id;
    END IF;
END $$;

-- Drop legacy knowledge tables (domain moved to sdkwork-knowledgebase).
DROP TABLE IF EXISTS a_agent_knowledge_sync_job;
DROP TABLE IF EXISTS a_agent_knowledge_binding;
DROP TABLE IF EXISTS a_agent_knowledge_index;
DROP TABLE IF EXISTS a_agent_knowledge_chunk;
DROP TABLE IF EXISTS a_agent_knowledge_document;
DROP TABLE IF EXISTS a_agent_knowledge_source;
DROP TABLE IF EXISTS a_agent_knowledge_base;

-- Drop legacy memory tables (domain moved to sdkwork-memory).
DROP TABLE IF EXISTS a_agent_memory_compaction_job;
DROP TABLE IF EXISTS a_agent_memory_access_event;
DROP TABLE IF EXISTS a_agent_memory_retrieval_index;
DROP TABLE IF EXISTS a_agent_memory_relation;
DROP TABLE IF EXISTS a_agent_memory_source;
DROP TABLE IF EXISTS a_agent_memory_record;
DROP TABLE IF EXISTS a_agent_memory_namespace;
DROP TABLE IF EXISTS a_agent_memory_binding;
DROP TABLE IF EXISTS a_agent_memory_profile;
DROP TABLE IF EXISTS a_agent_memory_store;

-- Drop legacy MCP marketplace table (domain moved to sdkwork-mcp).
DROP TABLE IF EXISTS a_agent_mcp_server;

-- Create composition slot table if not already created by baseline.
CREATE TABLE IF NOT EXISTS ai_agent_composition_slot (
    id BIGINT NOT NULL PRIMARY KEY,
    uuid VARCHAR(96) NOT NULL,
    tenant_id BIGINT NOT NULL,
    organization_id BIGINT NOT NULL DEFAULT 0,
    agent_id VARCHAR(128) NOT NULL,
    slot_id VARCHAR(128) NOT NULL,
    slot_kind VARCHAR(64) NOT NULL,
    target_module VARCHAR(64) NOT NULL,
    target_ref VARCHAR(256) NOT NULL,
    target_version_ref VARCHAR(128),
    priority INTEGER NOT NULL DEFAULT 0,
    enabled BOOLEAN NOT NULL DEFAULT TRUE,
    policy_json JSONB NOT NULL DEFAULT '{}'::jsonb,
    status SMALLINT NOT NULL DEFAULT 1,
    version BIGINT NOT NULL DEFAULT 0,
    created_at TIMESTAMPTZ NOT NULL,
    updated_at TIMESTAMPTZ NOT NULL,
    deleted_at TIMESTAMPTZ,
    CONSTRAINT uk_ai_agent_composition_slot_uuid UNIQUE (uuid),
    CONSTRAINT uk_ai_agent_composition_slot_tenant_agent_slot UNIQUE (tenant_id, agent_id, slot_id)
);

CREATE INDEX IF NOT EXISTS idx_ai_agent_composition_slot_lookup
    ON ai_agent_composition_slot (tenant_id, agent_id, slot_kind, enabled, priority, slot_id);

-- Create outbox event table if not already created by baseline.
CREATE TABLE IF NOT EXISTS ai_agent_outbox_event (
    id BIGINT NOT NULL PRIMARY KEY,
    uuid VARCHAR(64) NOT NULL,
    tenant_id BIGINT NOT NULL,
    aggregate_type VARCHAR(64) NOT NULL,
    aggregate_id BIGINT NOT NULL,
    event_type VARCHAR(128) NOT NULL,
    payload_json JSONB NOT NULL,
    status SMALLINT NOT NULL,
    created_at TIMESTAMPTZ NOT NULL,
    published_at TIMESTAMPTZ,
    version BIGINT NOT NULL DEFAULT 0,
    CONSTRAINT uk_ai_agent_outbox_event_uuid UNIQUE (tenant_id, uuid)
);

CREATE INDEX IF NOT EXISTS idx_ai_agent_outbox_event_status_created
    ON ai_agent_outbox_event (tenant_id, status, created_at);

-- folded migration: migrations/postgres/0002_ai_agent_refactor.up.sql
-- Migration: Upgrade to refactored schema v3
-- Transforms existing ai_* tables to professional design
-- Safe for production: idempotent, preserves existing data

-- ═══════════════════════════════════════════════════════
-- Step 1: Create helper functions
-- ═══════════════════════════════════════════════════════

CREATE OR REPLACE FUNCTION fnai_validate_capabilities_json(input TEXT)
RETURNS BOOLEAN
LANGUAGE plpgsql
IMMUTABLE
PARALLEL SAFE
AS $$
DECLARE
    payload JSONB;
BEGIN
    payload := input::jsonb;
    IF jsonb_typeof(payload) <> 'array' THEN
        RETURN FALSE;
    END IF;

    RETURN NOT EXISTS (
        SELECT 1
        FROM jsonb_array_elements(payload) AS elem(value)
        WHERE NOT (
            jsonb_typeof(elem.value) = 'string'
            AND char_length(elem.value #>> '{}') <= 128
            AND (elem.value #>> '{}') ~ '^[a-z0-9_-]+(\.[a-z0-9_-]+)+$'
        )
    )
    AND (
        SELECT COUNT(*)
        FROM jsonb_array_elements(payload) AS elem(value)
    ) = (
        SELECT COUNT(DISTINCT elem.value #>> '{}')
        FROM jsonb_array_elements(payload) AS elem(value)
    );
EXCEPTION WHEN others THEN
    RETURN FALSE;
END;
$$;

CREATE OR REPLACE FUNCTION fnai_is_standard_id(input TEXT, prefix TEXT DEFAULT NULL)
RETURNS BOOLEAN
LANGUAGE plpgsql
IMMUTABLE
PARALLEL SAFE
AS $$
BEGIN
    IF input IS NULL OR char_length(input) = 0 OR char_length(input) > 128 THEN
        RETURN FALSE;
    END IF;
    IF input !~ '^[a-z0-9_-]+(\.[a-z0-9_-]+)*$' THEN
        RETURN FALSE;
    END IF;
    IF prefix IS NOT NULL AND input NOT LIKE prefix || '%' THEN
        RETURN FALSE;
    END IF;
    RETURN TRUE;
END;
$$;

-- ═══════════════════════════════════════════════════════
-- Step 2: Convert TEXT JSON columns to JSONB
-- ═══════════════════════════════════════════════════════

-- ai_agent table
ALTER TABLE ai_agent
    ALTER COLUMN manifest_json TYPE JSONB USING manifest_json::jsonb,
    ALTER COLUMN manifest_json SET DEFAULT '{}'::jsonb;

ALTER TABLE ai_agent
    ALTER COLUMN default_code_task_intent_json TYPE JSONB USING default_code_task_intent_json::jsonb;

ALTER TABLE ai_agent
    ALTER COLUMN tags_json TYPE JSONB USING tags_json::jsonb,
    ALTER COLUMN tags_json SET DEFAULT '[]'::jsonb;

-- ai_agent_runtime_binding table
ALTER TABLE ai_agent_runtime_binding
    ALTER COLUMN capabilities_json TYPE JSONB USING capabilities_json::jsonb,
    ALTER COLUMN capabilities_json SET DEFAULT '[]'::jsonb;

-- ai_agent_deployment table
ALTER TABLE ai_agent_deployment
    ALTER COLUMN capabilities_snapshot_json TYPE JSONB USING capabilities_snapshot_json::jsonb,
    ALTER COLUMN capabilities_snapshot_json SET DEFAULT '[]'::jsonb;

-- ai_agent_audit_event table
ALTER TABLE ai_agent_audit_event
    ALTER COLUMN payload_json TYPE JSONB USING payload_json::jsonb;

-- ═══════════════════════════════════════════════════════
-- Step 3: Add L2 tenant_entity compliance fields
-- Per DATABASE_SPEC.md §5.3 L2 tenant_entity tables require:
--   id, uuid, created_at, updated_at, version, status, tenant_id, organization_id
-- ai_app_registry lacked uuid/version; ai_agent_runtime_binding and
-- ai_agent_deployment lacked organization_id. ai_agent already has all fields.
-- ═══════════════════════════════════════════════════════

-- ai_app_registry: add uuid (NOT NULL via backfill) and version
ALTER TABLE ai_app_registry
    ADD COLUMN IF NOT EXISTS uuid VARCHAR(64),
    ADD COLUMN IF NOT EXISTS version BIGINT NOT NULL DEFAULT 0;

-- Backfill uuid for existing rows that lack one. Stable format keeps
-- the value deterministic across re-runs. Idempotent via WHERE.
UPDATE ai_app_registry
SET uuid = 'app-registry-' || lpad(id::text, 12, '0')
WHERE uuid IS NULL;

ALTER TABLE ai_app_registry
    ALTER COLUMN uuid SET NOT NULL;

-- Add unique constraint on uuid if not present
DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint WHERE conname = 'uk_ai_app_registry_uuid'
    ) THEN
        ALTER TABLE ai_app_registry
            ADD CONSTRAINT uk_ai_app_registry_uuid UNIQUE (uuid);
    END IF;
END $$;

-- ai_agent_runtime_binding and ai_agent_deployment: add organization_id
ALTER TABLE ai_agent_runtime_binding
    ADD COLUMN IF NOT EXISTS organization_id BIGINT NOT NULL DEFAULT 0;

ALTER TABLE ai_agent_deployment
    ADD COLUMN IF NOT EXISTS organization_id BIGINT NOT NULL DEFAULT 0;

-- ═══════════════════════════════════════════════════════
-- Step 4: Add audit trail columns
-- ═══════════════════════════════════════════════════════

ALTER TABLE ai_agent
    ADD COLUMN IF NOT EXISTS created_by VARCHAR(128),
    ADD COLUMN IF NOT EXISTS updated_by VARCHAR(128),
    ADD COLUMN IF NOT EXISTS deleted_by VARCHAR(128);

ALTER TABLE ai_agent_runtime_binding
    ADD COLUMN IF NOT EXISTS created_by VARCHAR(128),
    ADD COLUMN IF NOT EXISTS updated_by VARCHAR(128);

ALTER TABLE ai_agent_deployment
    ADD COLUMN IF NOT EXISTS created_by VARCHAR(128);

ALTER TABLE ai_agent_composition_slot
    ADD COLUMN IF NOT EXISTS created_by VARCHAR(128),
    ADD COLUMN IF NOT EXISTS updated_by VARCHAR(128);

ALTER TABLE ai_app_registry
    ADD COLUMN IF NOT EXISTS created_by VARCHAR(128),
    ADD COLUMN IF NOT EXISTS updated_by VARCHAR(128);

-- ═══════════════════════════════════════════════════════
-- Step 5: Fix soft-delete unique constraints
-- ═══════════════════════════════════════════════════════

-- Drop old unique constraint and add partial unique index for soft-deletes
DO $$
BEGIN
    -- ai_agent: code uniqueness should only apply to non-deleted records
    IF EXISTS (
        SELECT 1 FROM pg_constraint WHERE conname = 'uk_ai_agent_tenant_code'
    ) THEN
        ALTER TABLE ai_agent DROP CONSTRAINT uk_ai_agent_tenant_code;
        CREATE UNIQUE INDEX uk_ai_agent_tenant_code
            ON ai_agent (tenant_id, code) WHERE deleted_at IS NULL;
    END IF;

    -- ai_agent_composition_slot: slot uniqueness should only apply to non-deleted records
    IF EXISTS (
        SELECT 1 FROM pg_constraint WHERE conname = 'uk_ai_agent_composition_slot_tenant_agent_slot'
    ) THEN
        ALTER TABLE ai_agent_composition_slot DROP CONSTRAINT uk_ai_agent_composition_slot_tenant_agent_slot;
        CREATE UNIQUE INDEX uk_ai_agent_composition_slot_tenant_agent_slot
            ON ai_agent_composition_slot (tenant_id, agent_id, slot_id) WHERE deleted_at IS NULL;
    END IF;
END $$;

-- ═══════════════════════════════════════════════════════
-- Step 6: Add missing indexes for query performance
-- ═══════════════════════════════════════════════════════

CREATE INDEX IF NOT EXISTS idx_ai_agent_tenant_visibility
    ON ai_agent (tenant_id, visibility, status)
    WHERE deleted_at IS NULL;

CREATE INDEX IF NOT EXISTS idx_ai_agent_composition_slot_target
    ON ai_agent_composition_slot (tenant_id, target_module, target_ref)
    WHERE deleted_at IS NULL;

CREATE INDEX IF NOT EXISTS idx_ai_agent_audit_tenant_org_created
    ON ai_agent_audit_event (tenant_id, organization_id, created_at DESC);

-- ═══════════════════════════════════════════════════════
-- Step 7: Update CHECK constraints to use helper functions
-- ═══════════════════════════════════════════════════════

-- Add new CHECK constraints (existing ones remain for backward compatibility)
ALTER TABLE ai_agent
    ADD CONSTRAINT ck_ai_agent_implementation_provider_id_v2 CHECK (
        implementation_provider_id IS NULL
        OR fnai_is_standard_id(implementation_provider_id, 'provider.')
    );

ALTER TABLE ai_agent_runtime_binding
    ADD CONSTRAINT ck_ai_agent_runtime_binding_capabilities_v2 CHECK (
        fnai_validate_capabilities_json(capabilities_json::text)
    );

-- ═══════════════════════════════════════════════════════
-- Step 8: Add foreign key constraints (if not exists)
-- ═══════════════════════════════════════════════════════

DO $$
BEGIN
    -- Add FK for runtime binding → agent
    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint WHERE conname = 'fk_ai_agent_runtime_binding_agent'
    ) THEN
        ALTER TABLE ai_agent_runtime_binding
            ADD CONSTRAINT fk_ai_agent_runtime_binding_agent
            FOREIGN KEY (tenant_id, agent_id)
            REFERENCES ai_agent(tenant_id, agent_id)
            ON DELETE CASCADE;
    END IF;

    -- Add FK for deployment → agent
    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint WHERE conname = 'fk_ai_agent_deployment_agent'
    ) THEN
        ALTER TABLE ai_agent_deployment
            ADD CONSTRAINT fk_ai_agent_deployment_agent
            FOREIGN KEY (tenant_id, agent_id)
            REFERENCES ai_agent(tenant_id, agent_id)
            ON DELETE CASCADE;
    END IF;

    -- Add FK for composition slot → agent
    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint WHERE conname = 'fk_ai_agent_composition_slot_agent'
    ) THEN
        ALTER TABLE ai_agent_composition_slot
            ADD CONSTRAINT fk_ai_agent_composition_slot_agent
            FOREIGN KEY (tenant_id, agent_id)
            REFERENCES ai_agent(tenant_id, agent_id)
            ON DELETE CASCADE;
    END IF;
END $$;

-- ═══════════════════════════════════════════════════════
-- Step 9: Create automatic updated_at trigger
-- ═══════════════════════════════════════════════════════

CREATE OR REPLACE FUNCTION fnai_update_updated_at()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $$
BEGIN
    NEW.updated_at = NOW();
    RETURN NEW;
END;
$$;

-- Drop and recreate triggers if they exist
DROP TRIGGER IF EXISTS trg_ai_agent_updated_at ON ai_agent;
CREATE TRIGGER trg_ai_agent_updated_at
    BEFORE UPDATE ON ai_agent
    FOR EACH ROW
    EXECUTE FUNCTION fnai_update_updated_at();

DROP TRIGGER IF EXISTS trg_ai_agent_runtime_binding_updated_at ON ai_agent_runtime_binding;
CREATE TRIGGER trg_ai_agent_runtime_binding_updated_at
    BEFORE UPDATE ON ai_agent_runtime_binding
    FOR EACH ROW
    EXECUTE FUNCTION fnai_update_updated_at();

DROP TRIGGER IF EXISTS trg_ai_agent_composition_slot_updated_at ON ai_agent_composition_slot;
CREATE TRIGGER trg_ai_agent_composition_slot_updated_at
    BEFORE UPDATE ON ai_agent_composition_slot
    FOR EACH ROW
    EXECUTE FUNCTION fnai_update_updated_at();

-- ═══════════════════════════════════════════════════════
-- Step 10: Create view for active agents with bindings
-- ═══════════════════════════════════════════════════════

CREATE OR REPLACE VIEW v_ai_agent_active_binding AS
SELECT
    a.id AS agent_id,
    a.agent_id AS agent_code,
    a.tenant_id,
    a.organization_id,
    a.owner_user_id,
    a.code,
    a.display_name,
    a.status,
    a.visibility,
    rb.binding_id,
    rb.provider_id,
    rb.implementation_kind,
    rb.capabilities_json,
    a.updated_at
FROM ai_agent a
LEFT JOIN ai_agent_runtime_binding rb
    ON a.tenant_id = rb.tenant_id
    AND a.agent_id = rb.agent_id
    AND rb.active = TRUE
WHERE a.deleted_at IS NULL;

-- ═══════════════════════════════════════════════════════
-- Step 11: Enable Row-Level Security (optional, uncomment to enable)
-- ═══════════════════════════════════════════════════════

-- NOTE: RLS should be enabled after testing in staging environment
-- Uncomment the following lines to enable tenant isolation at database level:

-- ALTER TABLE ai_agent ENABLE ROW LEVEL SECURITY;
-- ALTER TABLE ai_agent_runtime_binding ENABLE ROW LEVEL SECURITY;
-- ALTER TABLE ai_agent_deployment ENABLE ROW LEVEL SECURITY;
-- ALTER TABLE ai_agent_composition_slot ENABLE ROW LEVEL SECURITY;
-- ALTER TABLE ai_agent_audit_event ENABLE ROW LEVEL SECURITY;
-- ALTER TABLE ai_agent_outbox_event ENABLE ROW LEVEL SECURITY;

-- CREATE POLICY tenant_isolation_ai_agent ON ai_agent
--     USING (tenant_id = current_setting('app.current_tenant_id', true)::BIGINT);

-- ═══════════════════════════════════════════════════════
-- Step 12: Add table and column comments for documentation
-- ═══════════════════════════════════════════════════════

COMMENT ON TABLE ai_agent IS 'Agent business entity with identity, manifest snapshot, and lifecycle state';
COMMENT ON COLUMN ai_agent.manifest_json IS 'Full agent manifest as JSONB for structured queries';
COMMENT ON COLUMN ai_agent.status IS '0=draft, 1=active, 2=disabled, 3=archived, 4=deleted';
COMMENT ON COLUMN ai_agent.visibility IS '0=private, 1=internal, 2=public, 3=marketplace';

COMMENT ON TABLE ai_agent_runtime_binding IS 'Maps agents to provider runtime configurations with capability declarations';
COMMENT ON COLUMN ai_agent_runtime_binding.active IS 'Only one binding can be active per agent';

COMMENT ON TABLE ai_agent_deployment IS 'Immutable deployment history with provider configuration snapshots';
COMMENT ON COLUMN ai_agent_deployment.status IS '0=pending, 1=deployed, 2=rollback, 3=failed';

COMMENT ON TABLE ai_agent_composition_slot IS 'Binds agents to sibling module resources (memory, knowledge, skills, prompts, drive, mcp)';
COMMENT ON COLUMN ai_agent_composition_slot.slot_kind IS 'Resource type: memory, knowledge, skill, prompt, drive, tool, mcp';
COMMENT ON COLUMN ai_agent_composition_slot.target_module IS 'Sibling module owning the resource';
COMMENT ON COLUMN ai_agent_composition_slot.target_ref IS 'Reference ID to the resource in the target module';

COMMENT ON TABLE ai_agent_audit_event IS 'Immutable audit log for agent management operations';
COMMENT ON TABLE ai_agent_outbox_event IS 'Outbox pattern table for reliable cross-module event propagation';
COMMENT ON COLUMN ai_agent_outbox_event.status IS '0=pending, 1=published, 2=failed';

COMMENT ON VIEW v_ai_agent_active_binding IS 'Active agents with their current provider binding';

-- folded migration: migrations/postgres/0003_drop_unused_tables.up.sql
-- ═══════════════════════════════════════════════════════
-- Migration 0003: Drop unused tables (schema simplification v3)
-- ═══════════════════════════════════════════════════════
-- Removes 3 tables that were identified as dead code or over-designed:
--
-- 1. ai_app_registry — Dead code: schema + seed existed but zero business
--    reads in Rust source. Application identity is managed by IAM, not by
--    this table.
-- 2. ai_agent_deployment — Incomplete: only INSERT/LIST implemented, no
--    state machine transitions (promote/archive/rollback). Was effectively
--    a deployment log, not a lifecycle table. Removed to avoid confusion.
-- 3. ai_agent_outbox_event — Dead code: no publisher, no consumer, no
--    business transaction INSERTs. Outbox Pattern was designed (with monthly
--    partitioning + RLS) but never implemented. Removed as over-design.
--
-- Also removes 'deployment_created' from ai_agent_audit_event CHECK
-- constraint since deployment table no longer exists.
-- ═══════════════════════════════════════════════════════

-- Step 1: Drop ai_agent_outbox_event (no dependencies, safe to drop first)
DROP TABLE IF EXISTS ai_agent_outbox_event CASCADE;

-- Step 2: Drop ai_agent_deployment
-- Note: ai_agent_audit_event.action CHECK constraint references 'deployment_created'
-- We update the constraint before dropping the table to keep audit log consistent.
ALTER TABLE ai_agent_audit_event
    DROP CONSTRAINT IF EXISTS ck_ai_agent_audit_action;

ALTER TABLE ai_agent_audit_event
    ADD CONSTRAINT ck_ai_agent_audit_action CHECK (
        action IN (
            'created',
            'updated',
            'deleted',
            'restored',
            'status_changed',
            'started',
            'completed',
            'failed',
            'cancelled',
            'provider_binding_changed',
            'composition_slot_created',
            'composition_slot_updated',
            'composition_slot_deleted'
        )
    );

DROP TABLE IF EXISTS ai_agent_deployment CASCADE;

-- Step 3: Drop ai_app_registry
DROP TABLE IF EXISTS ai_app_registry CASCADE;
